#include "structures.h"

using namespace std;

vector<activity> activities = {
    {1, "Registan Square Guided Tour", "Samarkand",
        {"cultural","museum","photography","walk", "culture"},
        "from 0$ (museum +5$)", 5, 2,
        "Step into the heart of Samarkand at Registan Square, where three madrasahs shimmer with their turquoise tilework. A local guide reveals centuries of Silk Road stories, and you can stay until or revisit at sunset for photos of the lions-and-sun mosaics on Sher-Dor Madrasa."},
    {2, "Shah-i-Zinda Necropolis Hike", "Samarkand",
        {"historical","walk","architecture", "history"},
        "from 5$", 5, 1.5,
        "Go up the ancient steps to Shah-i-Zinda, the luminous necropolis of Samarkand, where you walk the narrow lanes between tile-draped mausoleums. Immerse yourself in the talent of medieval artisans and the majesty of the domes."},
    {3, "Siyob Bazaar Culinary Walk", "Samarkand",
        {"culinary","local-life","walk", "food"},
        "depends on your expenses", 0, 2,
        "Wander the busy aisles of Siyob Bazaar, Samarkand's oldest marketplace, sampling dried apricots, pilaf, and fresh flatbread. With a food-loving guide, you will taste Uzbek sweets, chat with spice merchants and uncover hidden cafes off the traditional tourist path."},
    {4, "Bibi-Khanym Mosque Sunset Visit", "Samarkand",
        {"mosque","cultural","photography", "culture"},
        "from 2$", 2, 1,
        "Visit the Bibi-Khanym Mosque as evening light bathes its vast courtyard. Once one of the largest mosques in the Islamic world, its monumental iwan and faded patterns create a serene space to shoot dramatic sky-dome photos."},
    {5, "Ulugh Beg Observatory and Museum", "Samarkand",
        {"educational","historical","museum", "history"},
        "from 4$", 4, 1.5,
        "Explore the 15th century Ulugh Beg Observatory, where the famed astronomer-emperor mapped the stars. Discover the ancient instruments and watch the sweeping views of Samarkand from the top."},
    {6, "Anhor Locomotive Park", "Tashkent",
        {"amusement","walking","family"},
        "from 5$", 5, 2,
        "Perfect for families, Locomotive Park features fun rides for all ages. It may get chilly with the water nearby, so grab a light jacket!"},
    {7, "Central Park", "Tashkent",
        {"walking","amusement","nature"},
        "free", 0, 2,
        "Enjoy a stroll or rent bicycles in Tashkent's Central Park. Between the amusement attractions and cafes, it is ideal for both leisure and family fun. Seasonal events add extra excitement."},
    {8, "Ashqobod Leisure Park", "Tashkent",
        {"walking","amusement","modern"},
        "from 3$", 3, 1.5,
        "Ashqobod Park blends modern attractions with open green spaces. Visitors can enjoy walking with a snack, fun amusement rides, and photo spots perfect for social media."},
    {9, "Magic City Park", "Tashkent",
        {"walking","shopping","modern"},
        "depends on your expenses", 0, 2,
        "Often called the Disneyland of Uzbekistan, Magic City Park combines retail, entertainment, and themed walking zones. Explore shops, take photos near the castle, and enjoy interactive experiences."},
    {10, "Oasis Waterpark", "Tashkent",
        {"swimming","family","modern"},
        "from 15$", 15, 3,
        "Oasis Waterpark offers slides, pools, and relaxation zones. Great for families or friends seeking a fun day out. Lifeguards and safety equipment ensure a secure visit."},
    {11, "Railway Museum", "Tashkent",
        {"train", "museum", "educational"},
        "from 2$", 2, 1.5,
        "Step back in time at the Tashkent Railway Museum, featuring historic engines and carriages. Perfect for locomotive enthusiasts and visitors interested in Uzbekistan's rail history."},
    {12, "State Museum of the Temurids", "Tashkent",
        {"museum", "history", "cultural", "educational", "historical", "culture"},
        "from 3$", 3, 2,
        "Discover the Timurid Empire through artifacts, detailed models, and historical documents. This museum is a must-visit for anyone interested in Central Asian history."},
    {13, "Museum of Victims of Political Repression", "Tashkent",
        {"historical", "museum", "educational", "cultural", "walk", "history", "culture"},
        "from 2$", 2, 1,
        "Learn about Uzbekistan's 20th century political history and the victims of repression through powerful exhibits and personal stories."},
    {100, "Po-i-Kalyan Minaret Visit", "Bukhara",
        {"historical","cultural","culture","history","architecture","photography"},
        "from 5$", 5, 2,
        "Stand beneath the towering Kalyan Minaret and wander the mosque and madrasa complex in Bukhara. The blue domes and carved stone tell the story of empires past and make great photo opportunities."},
    {101, "Lyab-i-Hauz Evening Walk", "Bukhara",
        {"walk","local-life","photography"},
        "depends on your expenses", 0, 1.5,
        "Relax around the reflecting pool of Lyab-i-Hauz at dusk, when teahouses light up and locals gather. The 17th century architecture and calm atmosphere make it perfect for an evening stroll."},
    {102, "Trading Domes (Toqi) and Bazaar Exploration", "Bukhara",
        {"local-life", "walk", "bazaar", "shopping"},
        "depends on your expenses, ideally 10$", 0, 1.5,
        "Explore Bukhara's medieval trading domes, where craftsmen sell textiles, ceramics, and spices. A blend of architecture, heritage, and shopping in one vibrant marketplace."}
};